FROM node:20-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    python3 \
    make \
    g++ \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY apps/backend/package.json apps/backend/package-lock.json ./
RUN npm install --legacy-peer-deps
RUN npm install -g pnpm @nestjs/cli

COPY apps/backend ./
RUN pnpm run build

ENV NODE_ENV=production

RUN groupadd --system --gid 1001 nodejs && useradd --system --uid 1001 -g nodejs nestjs

USER nestjs

EXPOSE 4000

CMD ["node", "dist/main"]
