packages:
  - "apps/*"
  - "packages/*"
  - "apps/contracts-helios/*"
  - "apps/founder-device/*"
  - "sdk/*"
allowBuilds:
  '@nestjs/core': set this to true or false
  esbuild: true
  keccak: true
  secp256k1: true
  sqlite3: set this to true or false
