services:
  - type: web
    name: synex-backend
    plan: free
    region: oregon
    runtime: node
    buildCommand: |
      cd apps/backend &&
      npm install &&
      npx nest build &&
      npm run db:generate &&
      npm run db:migrate
    startCommand: cd apps/backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: API_PREFIX
        value: api/v1
      - key: CORS_ORIGIN
        value: https://synex-frontend-faei.onrender.com
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@localhost:5432/synex?schema=public
      - key: REDIS_HOST
        value: localhost
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        value: ""
      - key: REDIS_DB
        value: "1"
      - key: JWT_SECRET
        value: change-me-in-production
      - key: JWT_REFRESH_SECRET
        value: change-me-in-production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: PLATFORM_TOKEN_ADDRESS
        value: "0x62248d00Bce13BE2D8838bDe86fEc95487949b89"
      - key: PLATFORM_TOKEN_SYMBOL
        value: LXON
      - key: PLATFORM_TOKEN_DECIMALS
        value: "18"
      - key: LXON_RPC_URL
        value: https://ethereum-sepolia.publicnode.com
      - key: ADMIN_EMAILS
        value: admin@lxon.ai
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      - key: SESSION_SECRET
        value: change-me-in-production
      - key: GOVERNANCE_VOTING_PERIOD_DAYS
        value: "7"
      - key: GOVERNANCE_QUORUM_PERCENTAGE
        value: "10"
      - key: STAKING_REWARD_RATE
        value: "12"
      - key: STAKING_LOCK_PERIOD_DAYS
        value: "30"
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /api/v1/health

  - type: web
    name: synex-frontend
    plan: free
    region: oregon
    runtime: node
    buildCommand: |
      cd apps/frontend &&
      npm install &&
      npm run build
    startCommand: cd apps/frontend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://synex-backend-xvwv.onrender.com/api/v1
      - key: NEXTAUTH_URL
        value: https://synex-frontend-faei.onrender.com
      - key: NEXTAUTH_SECRET
        value: change-me-in-production
      - key: NEXT_PUBLIC_APP_URL
        value: https://synex-frontend-faei.onrender.com
      - key: NEXT_PUBLIC_PLATFORM_TOKEN_ADDRESS
        value: "0x62248d00Bce13BE2D8838bDe86fEc95487949b89"
      - key: NEXT_PUBLIC_PLATFORM_TOKEN_SYMBOL
        value: LXON
