import { Chain } from '../../../modules/wallets/entities/wallet.entity';
import { TransactionType } from '../../../modules/transactions/entities/transaction.entity';
export declare const generateId: () => string;
export declare const isValidEthereumAddress: (address: string) => boolean;
export declare const normalizeAddress: (address: string) => string;
export declare const truncateAddress: (address: string, startLength?: number, endLength?: number) => string;
export declare const isZeroAddress: (address: string) => boolean;
export declare const getChainName: (chain: Chain) => string;
export declare const getChainExplorer: (chain: Chain) => string;
export declare const getChainCurrency: (chain: Chain) => string;
export declare const parseTransactionType: (type: string) => TransactionType | undefined;
export declare const formatUsd: (value: number | string, decimals?: number) => string;
export declare const formatPercentage: (value: number, decimals?: number) => string;
export declare const sleep: (ms: number) => Promise<void>;
export declare const chunkArray: <T>(array: T[], chunkSize: number) => T[][];
export declare const debounce: <T extends (...args: unknown[]) => void>(func: T, wait: number) => ((...args: Parameters<T>) => void);
export declare const throttle: <T extends (...args: unknown[]) => void>(func: T, limit: number) => ((...args: Parameters<T>) => void);
export declare const generateSecureRandomString: (length: number) => string;
export declare const sanitizeString: (input: string) => string;
export declare const isValidUrl: (url: string) => boolean;
export declare const maskSensitiveData: (data: Record<string, unknown>) => Record<string, unknown>;
