"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.configValidationSchema = void 0;
const zod_1 = require("zod");
exports.configValidationSchema = zod_1.z.object({
    NODE_ENV: zod_1.z.enum(['development', 'production', 'test']).default('development'),
    PORT: zod_1.z.coerce.number().positive().default(4000),
    API_PREFIX: zod_1.z.string().default('api/v1'),
    CORS_ORIGIN: zod_1.z.string().default('http://localhost:3000'),
    DATABASE_URL: zod_1.z.string().url(),
    DIRECT_URL: zod_1.z.string().url(),
    REDIS_HOST: zod_1.z.string().default('localhost'),
    REDIS_PORT: zod_1.z.coerce.number().positive().default(6379),
    REDIS_PASSWORD: zod_1.z.string().optional(),
    REDIS_DB: zod_1.z.coerce.number().positive().default(0),
    JWT_SECRET: zod_1.z.string().min(32),
    JWT_EXPIRES_IN: zod_1.z.string().default('7d'),
    JWT_REFRESH_SECRET: zod_1.z.string().min(32),
    JWT_REFRESH_EXPIRES_IN: zod_1.z.string().default('30d'),
    GOOGLE_CLIENT_ID: zod_1.z.string().optional(),
    GOOGLE_CLIENT_SECRET: zod_1.z.string().optional(),
    OPENAI_API_KEY: zod_1.z.string().startsWith('sk-').optional(),
    OPENAI_MODEL: zod_1.z.string().default('gpt-4-turbo-preview'),
    WALLETCONNECT_PROJECT_ID: zod_1.z.string().optional(),
    ETHEREUM_RPC_URL: zod_1.z.string().url().optional(),
    POLYGON_RPC_URL: zod_1.z.string().url().optional(),
    BSC_RPC_URL: zod_1.z.string().url().optional(),
    ARBITRUM_RPC_URL: zod_1.z.string().url().optional(),
    BASE_RPC_URL: zod_1.z.string().url().optional(),
    AVALANCHE_RPC_URL: zod_1.z.string().url().optional(),
    LXON_RPC_URL: zod_1.z.string().url().optional(),
    ETHERSCAN_API_KEY: zod_1.z.string().optional(),
    BSCSCAN_API_KEY: zod_1.z.string().optional(),
    POLYGONSCAN_API_KEY: zod_1.z.string().optional(),
    ARBISCAN_API_KEY: zod_1.z.string().optional(),
    BASESCAN_API_KEY: zod_1.z.string().optional(),
    SNOWTRACE_API_KEY: zod_1.z.string().optional(),
    LXONSCAN_API_KEY: zod_1.z.string().optional(),
    SMTP_HOST: zod_1.z.string().optional(),
    SMTP_PORT: zod_1.z.coerce.number().positive().default(587),
    SMTP_SECURE: zod_1.z.coerce.boolean().default(false),
    SMTP_USER: zod_1.z.string().optional(),
    SMTP_PASS: zod_1.z.string().optional(),
    EMAIL_FROM: zod_1.z.string().default('Synex <noreply@synex.ai>'),
    S3_BUCKET: zod_1.z.string().optional(),
    S3_REGION: zod_1.z.string().default('us-east-1'),
    S3_ACCESS_KEY: zod_1.z.string().optional(),
    S3_SECRET_KEY: zod_1.z.string().optional(),
    IPFS_GATEWAY: zod_1.z.string().url().default('https://ipfs.io/ipfs/'),
    RAZORPAY_KEY_ID: zod_1.z.string().optional(),
    RAZORPAY_KEY_SECRET: zod_1.z.string().optional(),
    RAZORPAY_WEBHOOK_SECRET: zod_1.z.string().optional(),
    STRIPE_SECRET_KEY: zod_1.z.string().optional(),
    STRIPE_WEBHOOK_SECRET: zod_1.z.string().optional(),
    ADMIN_EMAILS: zod_1.z.string().default('admin@synex.ai'),
    BCRYPT_ROUNDS: zod_1.z.coerce.number().positive().default(12),
    RATE_LIMIT_WINDOW_MS: zod_1.z.coerce.number().positive().default(900000),
    RATE_LIMIT_MAX_REQUESTS: zod_1.z.coerce.number().positive().default(100),
    SESSION_SECRET: zod_1.z.string().min(32),
    FRONTEND_URL: zod_1.z.string().url().default('http://localhost:3000'),
    PLATFORM_TOKEN_ADDRESS: zod_1.z.string().optional(),
    PLATFORM_TOKEN_SYMBOL: zod_1.z.string().default('LXON'),
    GOVERNANCE_VOTING_PERIOD_DAYS: zod_1.z.coerce.number().positive().default(7),
    GOVERNANCE_QUORUM_PERCENTAGE: zod_1.z.coerce.number().positive().default(10),
    STAKING_REWARD_RATE: zod_1.z.coerce.number().positive().default(12),
    STAKING_LOCK_PERIOD_DAYS: zod_1.z.coerce.number().positive().default(30),
    LOG_LEVEL: zod_1.z.enum(['error', 'warn', 'info', 'debug']).default('info'),
});
//# sourceMappingURL=config.schema.js.map